### ISSUE TITLE
Suicide Problems

### ISSUE THREAD

**Issue by DoktorSAS** [XLabsProject/s1x-client#101]
### Suicide Problems
I am moving the commands I have in chat into console commands by working on the Master Project version. What happens is that in 3 different ways of calling the function they react in completely different ways.

### CMD Execution
Through CMD I send a notification that is received by the script in Lua. From there Lua calls the suicide function and what happens is that the screen becomes bloody but the player does not die.
I have also tried creating a function linked to the entity to execute self:suicide() the result is the same 
```
 local onDieNotify = player:onnotify("_die", function()
        player:suicide()
 end)
```
### Chat Execution
I have created a function to manage the chat is when the die command is received the player is killed. In this case everything works correctly.
```
function entity:onPlayerMessage()
          ...
          if msg[1] == "die" then
                self:suicide()
          end
end
```
### Notfiy Execution
On receiving any Notify the player dies, only after a few seconds. In fact the body duplicates but the player is able to move and see the duplicate body.

### Video
https://streamable.com/q31slc

**Comment by diamante0018** [comment]
When the chat notify is sent the thread_local pointer for bgs_t structure is cleared and therefore it is too late to call the suicide function

**Comment by diamante0018** [comment]
This is now fixed after the notifies have been wrapped by the scheduler
