### ISSUE TITLE
Please upload the download file on mega file im happy to give you all $10 for you to do that on a premium mega file account

### ISSUE THREAD

**Issue by ShotzzAU** [XLabsProject/s1x-client#104]
The current torrent file is very slow and i have extremely high speeds many others are reporting issues we can fix this issue but uploading it on mega it just costs $10 which im happy to give

**Comment by KarrarJ-Ali** [comment]
Dm me on discord **BL4CKZ375U#5338** and send me your Gmail, I'll share a G drive folder with you and you can upload it to mega yourself

**Comment by kingTaven** [comment]
Do notice that if mega or even gdrive catches wind they'll remove it. Idk why something like this would be posted here when its not an issue at all.

**Comment by ShotzzAU** [comment]
huh its a issue im literally getting 500kbps speed when i have 1 quarter of a gigabyte it says 3 days to download usually i can download a 100gb file in under 1 hour

**Comment by kingTaven** [comment]
> 
> 
> huh its a issue im literally getting 500kbps speed when i have 1 quarter of a gigabyte it says 3 days to download usually i can download a 100gb file in under 1 hour

You obviously don't understand how torrents work. Have a good one.

**Comment by ShotzzAU** [comment]
help me understand how they work?
