### ISSUE TITLE
series x controller

### ISSUE THREAD

**Issue by NasCLXW** [XLabsProject/s1x-client#105]
series x controller does not work, only rumble.

**Comment by mjkzy** [comment]
don't think this is exactly a S1x issue as it uses the native controller support. even then, it should still work. have you made sure you have the correct drivers for the controller and that controller is enabled?

**Comment by NasCLXW** [comment]
I updated drivers on Xbox series x and tried to play on Bluetooth and wired, still does not work.

**Comment by TheBenBro** [comment]
If anyone is still having this issue, I managed to fix it by going to Settings->Controller->General Controller Settings, then unchecking xbox config support, and general gamepad config support. This will probably remove support for other steam games so turn it on when you want to play other games.
