### ISSUE TITLE
Unable to connect to servers

### ISSUE THREAD

**Issue by xTazter** [XLabsProject/s1x-client#106]
When joining any server from the server list i get to the loading screen, but once the map is fully loaded it gets stuck on "Syncronizing game settings" and disconnects me after a minute or two.
I then get the error message "Lost connection to Host/Server. Connection timed out."
Hosting my own private match games works fine though.
As a heads up, i dont own the Steam version of AW!
I also have moderate NAT which could possibly be the reason, but i think it would still let me into one of the servers.

pictures: https://prnt.sc/11s5vrw and https://prnt.sc/11s5xuy

**Comment by gospehl** [comment]
Did u figure it out ?

**Comment by momo5502** [comment]
> Did u figure it out ?

No

**Comment by momo5502** [comment]
Seems to have been resolved. Nobody complains anymore

**Comment by Pengu8775** [comment]
I still have this issue, was it solved?
