### ISSUE TITLE
XBOX series X controller not working

### ISSUE THREAD

**Issue by NasCLXW** [XLabsProject/s1x-client#109]
Drivers are updated, I tried nearly everything and had help from the X Labs server and so far nothing worked.
PS4 controller worked fine but not the series x controller. There is rumble when I shoot with my mouse but input does not work for S1X.

**Comment by momo5502** [comment]
You already created issue #105 and we closed it. Please don't create another issue in such cases.
S1x controller support comes from the native game/steam. If that has issues, it won't be fixed, because I don't have such a controller to test things with.
