### ISSUE TITLE
Investigate performance issues 

### ISSUE THREAD

**Issue by momo5502** [XLabsProject/s1x-client#11]
I assume this is related to Arxan's Hardware-Breakpoint-based control flow.

https://www.youtube.com/watch?v=aa1ZCdPud5g

**Comment by ChxseH** [comment]
I wonder if the "duplicate keys" is a part of this issue.

https://youtu.be/kyvQFdm2Tqo?t=27

Seems to happen after opening the console/scoreboard

Putting the game in borderless window fixes this.

**Comment by momo5502** [comment]
No, this issue is very likey caused by arxan. The shift issue has been in the COD forever afaik

**Comment by momo5502** [comment]
Fixed and confirmed
