### ISSUE TITLE
Missing commands for MP

### ISSUE THREAD

**Issue by BoxOfMysteriez** [XLabsProject/s1x-client#113]
Some commands are missing from the MP portion of S1. 

/g_speed
/g_gravity
/jump_height (the normal one for non-exo gameplay not high_jump_height)
/timescale (may cause instability) 

I'll update this list with any others I'm made aware of

**Comment by diamante0018** [comment]
These "commands" also known as dvars are not present in the game.
Implementation of these dvars will most likely require a very deep understanding of the engine.
Or perhaps they simply changed the name of these dvars?
I can see that there are a lot of dvars related to gravity like "no_gravity" you can try to experiment with these and report back your findings.

**Comment by BoxOfMysteriez** [comment]
> These "commands" also known as dvars are not present in the game.
> Implementation of these dvars will most likely require a very deep understanding of the engine.
> Or perhaps they simply changed the name of these dvars?
> I can see that there are a lot of dvars related to gravity like "no_gravity" you can try to experiment with these and report back your findings.

 Some of these if not all already already implemented into the Campaign portion of S1 and previous clients. Also, all the old cod titles share similar if not exactly the same dvars. The names of these, like speed or jump height, don't change from SP to MP in any other COD so I don't see why AW would be any different.

**Comment by diamante0018** [comment]
Reminder for myself only gravity was implemented
