### ISSUE TITLE
Implement Listassetpool filter similar to IW6x

### ISSUE THREAD

**Issue by Slykuiper** [XLabsProject/s1x-client#123]
IW6x has a filter for listassetpool so all queries aren't dumped into console, so its easier to browse what you're looking for. Would be great for S1x

**Comment by diamante0018** [comment]
My bad I didn't mention this issue in the commit I made yesterday. (Can be closed?) @momo5502

**Comment by momo5502** [comment]
Oh yeah

**Comment by momo5502** [comment]
https://github.com/XLabsProject/s1x-client/commit/744861120b90dc7b46e793cdb3cc1062a3987526
