### ISSUE TITLE
Dedicated server process priority reset after each map loaded.

### ISSUE THREAD

**Issue by xerxes-at** [XLabsProject/s1x-client#124]
I did notice this on dedicated servers they are changing the priority to normal after every map load.
I did test this on the release version and latest dev build.

Steps to reproduce:
Start server with a process priority != normal
load a map (map or map_rotate)
process priority is now back to normal.

**Comment by diamante0018** [comment]
That was because of a patch implemented in dedicated.cpp that has since been removed.
This issue should now be solved.
