### ISSUE TITLE
Custom Classes 11-60 doesn't saves

### ISSUE THREAD

**Issue by clx127** [XLabsProject/s1x-client#126]
Yesterday i've made 40 custom class but today when i launch game i see that only 10 custom class are saved, other 30 it just disappeared...
Is it bug?

**Comment by momo5502** [comment]
#50

**Comment by clx127** [comment]
Sorry if it was posted, but can it be a fixed?)

**Comment by momo5502** [comment]
If someone works on it, yes. But for now we have so many things to work on, that i can't promise it'll be fixed anytime soon
