### ISSUE TITLE
Adding Level Var support

### ISSUE THREAD

**Issue by DoktorSAS** [XLabsProject/s1x-client#132]
### Adding Level Var support
In GSC it is possible to modify level variables to enable and disable certain game mechanics. It would be very useful to have access to level dvars. 
For example, the variable level.players can make the job of someone making a script with Lua support much easier. Using this would allow a scripter a system to edit player data without having to look in an external list.
I've spoken to fed a bit and he's already started working on it. 
My idea is an idea I do not know if it is possible and how complex it is to implement.

**Comment by momo5502** [comment]
Definitely possible. I would actually support this idea. It would also make debugging the game's gsc code through external scripts simpler

**Comment by diamante0018** [comment]
The feature was added (not all tokens may have been labelled) so I'm closing this.
