### ISSUE TITLE
Fatal Error after leave lobby

### ISSUE THREAD

**Issue by clx127** [XLabsProject/s1x-client#143]
Client version 1.0.1, played in private match then when i want to quite game then i press Leave Lobby and after that my game crashed with fatal error. Before new release all was fine
[s1x-crash-2-2021-04-26-19-40-54.zip](https://github.com/XLabsProject/s1x-client/files/6377501/s1x-crash-2-2021-04-26-19-40-54.zip)
[s1x-crash-2-2021-04-26-19-40-56.zip](https://github.com/XLabsProject/s1x-client/files/6377502/s1x-crash-2-2021-04-26-19-40-56.zip)

**Comment by diamante0018** [comment]
Can't reproduce on newer builds so this probably got fixed
