### ISSUE TITLE
Zombie Close after starting private match

### ISSUE THREAD

**Issue by NexusX1** [XLabsProject/s1x-client#157]
Zombies Just spawns me in spectating then ends the match when ever i load into a private match idk why sorry if a fix has been posted somewhere.

**Comment by NexusX1** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/83496160/116778722-4573b200-aa39-11eb-83c2-d4575cbc9a7c.png)

**Comment by myanmeischump** [comment]
hi nexusx1 i have tested this issue,it seems like it doesnt work on outbreak and carrier but you will be able to play on decontamination and decent, i have no idea why u cant play outbreak or carrier its weird but anyways hope this helped

**Comment by diamante0018** [comment]
Yeah this bug does not happen on newer builds on the client, I tried as well. I guess it's resolved.

**Comment by myanmeischump** [comment]
diamante08 mine does the same thing but my xlabs launcher is updated though????
