### ISSUE TITLE
Add game[][] matrix access

### ISSUE THREAD

**Issue by DoktorSAS** [XLabsProject/s1x-client#161]
# Add game[][] matrix access
In gsc the game array/matrix allows access to variables that change according to player, game, map and other factors.
Adding a facility to receive this information, set this information and use this information would allow scripting support to modify/improve the experience of a scripted server game.
It could be used to maybe change some specific string and put credits on it or show the server staff online. It can be a good alternative to elements in the hud that can spoil the gaming experience.
It can be used to find and use appropriate names and phrases for a specific event.
For GunGame it would be nice to see the name of the winner team and not just "Your team Won". Also because the mode also works on TDM.

I do not know if it is possible to make this work and how difficult it is. Mine is an idea that may be interesting.

![](https://media.discordapp.net/attachments/811530234548453377/838523108301340682/unknown.png)
![](https://media.discordapp.net/attachments/811530234548453377/838513307811577977/unknown.png)
![](https://media.discordapp.net/attachments/811530234548453377/838516267605688350/unknown.png)

**Comment by Slykuiper** [comment]
This works well to return variables in the game array, but doesn't work with two dimensional arrays.

To return game["state"] I can call game:getgamevar().state, but I can't return a variable like game["strings"]["axis_name"]
