### ISSUE TITLE
Possible duplicate GUID

### ISSUE THREAD

**Issue by efinst0rm** [XLabsProject/s1x-client#166]
Hey,

Seem that there is a duplicate GUID issue. This GUID 77E90ECD6AD5F9F8 has over 390 connections and has people contacting from all over the world

**Comment by DoktorSAS** [comment]
![image](https://user-images.githubusercontent.com/62484597/116937361-67ec1200-ac69-11eb-8436-28befc3be370.png)
![image](https://user-images.githubusercontent.com/62484597/116937379-6f132000-ac69-11eb-93fd-491f839ffa1b.png)
![image](https://user-images.githubusercontent.com/62484597/116937428-7afee200-ac69-11eb-9e3d-52a2a052e384.png)
![image](https://user-images.githubusercontent.com/62484597/116937443-805c2c80-ac69-11eb-9566-250711bf971f.png)

Can be the same issue of Vekays and Potter. They made a tutorial on how to download(on iw4x) the game and left the download of their game. Inside these files they left the files in which the guides are contained and by doing so they made sure that several users would enter the server with the same name and guid.  i can try to investigate and see if it is the same problem as these two youtubers/streamers.

**Comment by mjkzy** [comment]
@DoktorSAS don't think that may be the issue as the GUID is generated by the master server, right? if not then that most likely could be it

**Comment by momo5502** [comment]
The GUID is generated based on your SMBIOS UUID. That might probably not be unique enough and I will seek for more deterministic HW-based entropy.
