### ISSUE TITLE
Support randomizing the map rotation

### ISSUE THREAD

**Issue by momo5502** [XLabsProject/s1x-client#169]

**Comment by Joelrau** [comment]
Couldn't you just use a script for that?

**Comment by momo5502** [comment]
Adding a dvar that enables shuffling seems more straight forward and reusable to me. Ofc a script would work, but why even implement map rotation in the first place then if anything could be done with a script?

**Comment by Joelrau** [comment]
I've done this in cods before with a script, so that seemed like the way to do it. But I do agree this would be a nice feature.

**Comment by diamante0018** [comment]
I coded this for iw4x so I will port the feature when I can

**Comment by diamante0018** [comment]
The time is now! Totally forgot to do this!
