### ISSUE TITLE
I have yet to be able to play because of this bug.

### ISSUE THREAD

**Issue by CCLA1902** [XLabsProject/s1x-client#180]
It would be really nice to get some help.
![image](https://user-images.githubusercontent.com/83595427/117941914-280fd500-b2d0-11eb-951b-033cd38f1001.png)
[s1x-crash-2-2021-05-01-19-07-53.zip](https://github.com/XLabsProject/s1x-client/files/6464583/s1x-crash-2-2021-05-01-19-07-53.zip)
[s1x-crash-2-2021-05-01-19-13-08.zip](https://github.com/XLabsProject/s1x-client/files/6464584/s1x-crash-2-2021-05-01-19-13-08.zip)
[s1x-crash-2-2021-05-03-09-27-18.zip](https://github.com/XLabsProject/s1x-client/files/6464585/s1x-crash-2-2021-05-03-09-27-18.zip)
[s1x-crash-2-2021-05-03-09-36-01.zip](https://github.com/XLabsProject/s1x-client/files/6464586/s1x-crash-2-2021-05-03-09-36-01.zip)
[s1x-crash-2-2021-05-05-07-14-21.zip](https://github.com/XLabsProject/s1x-client/files/6464587/s1x-crash-2-2021-05-05-07-14-21.zip)
[s1x-crash-2-2021-05-05-07-19-00.zip](https://github.com/XLabsProject/s1x-client/files/6464588/s1x-crash-2-2021-05-05-07-19-00.zip)
[s1x-crash-2-2021-05-05-08-06-50.zip](https://github.com/XLabsProject/s1x-client/files/6464589/s1x-crash-2-2021-05-05-08-06-50.zip)
[s1x-crash-2-2021-05-06-13-16-26.zip](https://github.com/XLabsProject/s1x-client/files/6464590/s1x-crash-2-2021-05-06-13-16-26.zip)
[s1x-crash-2-2021-05-10-00-28-42.zip](https://github.com/XLabsProject/s1x-client/files/6464591/s1x-crash-2-2021-05-10-00-28-42.zip)
[s1x-crash-2-2021-05-12-03-09-41.zip](https://github.com/XLabsProject/s1x-client/files/6464592/s1x-crash-2-2021-05-12-03-09-41.zip)
[s1x-crash-2-2021-05-12-03-13-34.zip](https://github.com/XLabsProject/s1x-client/files/6464593/s1x-crash-2-2021-05-12-03-13-34.zip)

**Comment by mjkzy** [comment]
@CCLA1902 does this happen right as you get into the main menu? the error you got every time leads back to a network-related function, so I assuming it's a network issue on the game's end or your end.

are you running the game with your PC internet on and are you on ethernet or wireless?

**Comment by CCLA1902** [comment]
I get the error when I try to load into any multiplayer game I am on an ethernet connection.

**Comment by CCLA1902** [comment]
https://imgur.com/xEHS3ej

**Comment by CCLA1902** [comment]
if that helps in the slightest

**Comment by mjkzy** [comment]
looks like you connect to S1x's server and fetch servers just fine, so it may just be a Demonware issue. i'll check it out but @momo5502 is the person who would probably know best.

**Comment by CCLA1902** [comment]
ok how do i get him to look at it?

**Comment by mjkzy** [comment]
he (or someone else) will most likely check this issue within the next couple days as he said he'll have time to work on the project some more.

**Comment by CCLA1902** [comment]
ok :) thank you for trying to help   
I put out a different post like 2 weeks ago and no one said anything
:)

**Comment by mjkzy** [comment]
ah, i see it. just because a reply isn't given doesn't mean it's being looked at/worked on. it's just, you don't tend to get a response due to the person being busy, or they don't know a solution/fix yet. i'd say go close your other issue (#165) and keep this one up.

**Comment by CCLA1902** [comment]
k

**Comment by diamante0018** [comment]
You have to switch to the experimental update channel of the launcher. This issue is completely irrelevant to your case.

**Comment by SobZ2** [comment]
So my error is not the same as the original issue, I didnt notice this at first. Instead of error 0x0000000014.... its just zeroes.
![image](https://user-images.githubusercontent.com/117935939/201170406-1d801388-5c4f-4d6f-8ddc-ace35d7aa218.png)

Pd:
I tried to switch to experimental but in that case the game wont even open.

**Comment by diamante0018** [comment]
Make sure you wait for the launcher to update all the files? If this is single player it will be fixed in experimental

**Comment by diamante0018** [comment]
You fixed the first crash, now you are getting a new one.
Please wait.

**Comment by SobZ2** [comment]
Doesn't seem like a quick fix right? XD

**Comment by diamante0018** [comment]
I haven't even tried fixing it.
You may have to wait indefinitely. Imagine that

**Comment by SobZ2** [comment]
Ah splendid
