### ISSUE TITLE
Fatal error with test build

### ISSUE THREAD

**Issue by Brentdevent** [XLabsProject/s1x-client#193]
Most of the times I get a fatal error when starting multiplayer/zombies with the latest test build. It doesn't happen with the release version 1.0.3. Everything is up to date. using the latest `Nvidia driver version 466.27`

[s1x-crash-5-2021-05-17-12-43-23.zip](https://github.com/XLabsProject/s1x-client/files/6493271/s1x-crash-5-2021-05-17-12-43-23.zip)

**Comment by momo5502** [comment]
Crashes in the nvidia driver.
