### ISSUE TITLE
"The Call of Duty: Advanced Warfare service is not available at this time. Please try again later."

### ISSUE THREAD

**Issue by Flamepaw17** [XLabsProject/s1x-client#194]
Sometimes it kicks from the multiplayer menus and gets this message. Other times it disconnects from the loading screen on a match and it gets this message. It even happens when trying to load a private match with bots, or a solo match in Exo Zombies. 
![unknown-38](https://user-images.githubusercontent.com/84364148/118584244-93402800-b764-11eb-84bf-b8a7f549df85.png)

**Comment by OneFourOne** [comment]
#172 fixes this. Compile your own build or wait for the next release.
