### ISSUE TITLE
Ability to view ones own GUID

### ISSUE THREAD

**Issue by callanb** [XLabsProject/s1x-client#201]
One potential place to implement this could be on the about section of the launcher.

The reason I am proposing this feature is to allow for easier verification of individuals playing on the platform. My specific use case is for whitelisting certain players on a server to facilitate a competitive match established outside of the game (Think [faceit](https://www.faceit.com/en/home), for example), though I can imagine this has other applications too.

I am aware that (And this is the implementation I am currently using) you can get a players GUID using a script on a server, however this adds an additional user inconvenience in addition to having to maintain a server that simply fulfils the purpose of verification.

Thanks for reading.

**Comment by codpcleague** [comment]
This would be very useful, please consider. Thank you.

**Comment by DoktorSAS** [comment]
I also find it very useful to have a feature to get the guid not from the server side or not using scripts. Creating servers with limited access can allow you to create servers with certain styles of gameplay such as competitive. But it can also be useful for servers dedicated to sniping or trickshotting only (even if they are small communities compared to competitive).
The idea of competitive servers can also allow to organise some small tournaments that can give a new face to the S!x client.

**Comment by momo5502** [comment]
The `guid` console command now exists which prints your guid to the console
