### ISSUE TITLE
Fatal error crash

### ISSUE THREAD

**Issue by Flamepaw17** [XLabsProject/s1x-client#223]
Game crashed shortly after selecting create a class and I get this issue. My PC's drivers are up to date and no luck. 
![Capture](https://user-images.githubusercontent.com/84364148/122625327-933c8c00-d072-11eb-9cfb-9870b384b6ad.PNG)

**Comment by diamante0018** [comment]
Too old, and the exception address points to a crasg in the client.
This hasn't happened anymore so I assume it was fixed.
