### ISSUE TITLE
S1X ERROR (Multiplayer mode does not run)

### ISSUE THREAD

**Issue by MAIBO22** [XLabsProject/s1x-client#238]
Currently the game is presenting me with a problem and it is that when I want to play in online mode it does not allow me, in singleplayer mode I can play perfectly but when I want to play online it does not leave me this "error".

It should be noted that I have everything related to updates up to date

[s1x-crash-2-2021-07-22-15-20-58.zip](https://github.com/XLabsProject/s1x-client/files/6864748/s1x-crash-2-2021-07-22-15-20-58.zip)
![image](https://user-images.githubusercontent.com/87830354/126697736-330477a4-688c-4423-af95-42dc0165b551.png)

**Comment by XCyberWarpX** [comment]
Try running SFC in command prompt with the command `sfc /scannow` to see if you have any corrupted windows files.

**Comment by TDawg262** [comment]
Been having this issue as well, and only recently. Maybe it's the new update or something, since the game was running perfectly fine before.

Either way, I really hope this gets fixed...

**Comment by diamante0018** [comment]
Issue is too old to work with. The crash appears to happen outside of the game and our client.
If OP or others involved want to try again they will have to use the latest build of S1x

Closing as stale
