### ISSUE TITLE
Client stutters apx every 60 seconds (mp only)

### ISSUE THREAD

**Issue by BoxOfMysteriez** [XLabsProject/s1x-client#25]
The client seems to stutter or hiccup for me about every 60 seconds in anything other then campaign. It's noticeable in any of the menus past the initial "Play Online" screen. I did not experience this with the vanilla game on steam. Assuming this is a drm/demonware related issue?

Running a clean steam build with S1x v0.0.1-54-g260cfe2

**Comment by momo5502** [comment]
083ec78efb8f7c6b3b51079f6a06ea837a1addf1
