### ISSUE TITLE
s1x not working

### ISSUE THREAD

**Issue by THE3ND68** [XLabsProject/s1x-client#305]
so i have a problem with both singleplayer and multiplayer. singelplayer doesn't even start. it just crashes the second i try to open it with this error: fatal error. disk read error 'code_post_gfx'. and multiplayer crashes when i go in to private match to set up a class with this error: fatal error. disk read error 'patch_mp_vlobby_room'. how do i fix them?

**Comment by mjkzy** [comment]
seems like corrupted game files

**Comment by Dss0** [comment]
broken aw game files like mjkzy said. this has nothing to do with s1x itself and doesn't belong here.
