### ISSUE TITLE
updating game settings pregame

### ISSUE THREAD

**Issue by Lurkzy** [XLabsProject/s1x-client#327]
in reference to #202 this happens when you change your timelimit to unlimited in pregame, once you're ingame you can use 'scr_gametype_timelimit 0' for unlimited time but pregame it causes the client to hang and you cannot /quit or /disconnect. I believe it also happens with some other options although I haven't tested it too much.

here is a reference to what happens: [https://streamable.com/d4yypb](url)

**Comment by diamante0018** [comment]
Duplicate of #202
