### ISSUE TITLE
Everything unlocked regardless of rank - Experimental Branch

### ISSUE THREAD

**Issue by Postalityjr-hub** [XLabsProject/s1x-client#331]
Everything is unlocked even being Rank 1, I know its normally like that because ranked did not work before, but on the experimental branch ranking is working but regardless it doesnt matter much because everything is unlocked right away no matter what rank you may be

**Comment by mjkzy** [comment]
Will port something shortly to fix this.

**Comment by Postalityjr-hub** [comment]
> 

That would be awesome, thank you!
