### ISSUE TITLE
Some Controllers are no longer working

### ISSUE THREAD

**Issue by TheSoliderror** [XLabsProject/s1x-client#353]
I have seen multiple people asking why controllers are not working on s1x. Idk what the issue is but it seems to have happened right before the ranked update was added. Ds4 windows does not work as well as Xbox 1 controllers.

**Comment by TheSoliderror** [comment]
Take this all with a grain of salt, I don't use controllers, this is just going off what others have told me. If there is any input you can tell me on this to help those people out please do.

**Comment by momo5502** [comment]
Why are you creating issues if you don't experience them yourself?

**Comment by TheSoliderror** [comment]
That's a great question, however I was going to close this issue today, but when I went to do so it was already closed. Sorry for the waist of time, that's on me.
