### ISSUE TITLE
Getting error when launching the game

### ISSUE THREAD

**Issue by z0mbieslayer** [XLabsProject/s1x-client#38]
Every time I try to launch the game, I get `Fatal error (0xC0000005) at Ox00007FF9AAF1FC0C. A minidump has been written. 
Make sure to update your graphics card drivers and install operating system updates!`. The minidump is attached. And yes, my graphics card and windows are both up to date. 
[s1x-crash-2-2021-03-17-13-19-05.zip](https://github.com/XLabsProject/s1x-client/files/6158297/s1x-crash-2-2021-03-17-13-19-05.zip)

**Comment by momo5502** [comment]
It's crashing in the steamclient. Disable steam to fix this for now

**Comment by momo5502** [comment]
Either this is an update to steam's internal api and we will have to adapt to it, which would mean others will get this error as well, sooner or later, or it's a bug in their api and it will probably be fixed with an update.

**Comment by z0mbieslayer** [comment]
Yup, closing steam seemed to fix it, thanks so much :)

**Comment by Sarmad69** [comment]
I just download the game and every time i click on singlrplayer or multiplayer it doesnt open the game please help meeee
