### ISSUE TITLE
Steam Files causing "Outdated Game Files" error.

### ISSUE THREAD

**Issue by zVPG** [XLabsProject/s1x-client#39]
Version: S1x: v0.0.1-106-ge7721f6

Despite having the latest version of Steam files (and DLC) When launching I was given the prompt that my game files we're out of date and needed to be updated. I was able to proceed into the client without issues however. 
![image](https://user-images.githubusercontent.com/46054954/111887120-ee41e280-89a0-11eb-937c-7206460b5307.png)

Update: Game has now gone from giving the prompt above to just crashing when I attempt to boot. I have a
ttached minidump file below
[s1x-crash-2-2021-03-20-18-04-36.zip](https://github.com/XLabsProject/s1x-client/files/6176546/s1x-crash-2-2021-03-20-18-04-36.zip)

**Comment by momo5502** [comment]
First issue will be fixed soon, second issue (crash) is related to an issue in our build infrastructure.
