### ISSUE TITLE
The xlabs launcher keeps showing this error message on launch.

### ISSUE THREAD

**Issue by ronaldblue001** [XLabsProject/s1x-client#403]
![image](https://user-images.githubusercontent.com/91916165/176884106-3e48a5b5-d67e-4f46-b51a-b2b1d8dd0989.png)
Every time I open the launcher it shows me the error above and even after I deleted the s1x folder to play other games from the launcher it still shows the error above.

**Comment by diamante0018** [comment]
Come to xlabs discord server and find the support channels. This is unrelated to s1x.
Thanks.
