### ISSUE TITLE
Fatal error when executing command prestigeReset

### ISSUE THREAD

**Issue by Brentdevent** [XLabsProject/s1x-client#43]
When I use the console command `prestigeReset`, I get a `Fatal error (0xC0000005) at 0x000000014053F3F8`.
See minidumps (It creates 2 dumps)

[s1x-crash-2-2021-03-21-23-21-44.zip](https://github.com/XLabsProject/s1x-client/files/6178517/s1x-crash-2-2021-03-21-23-21-44.zip)
[s1x-crash-2-2021-03-21-23-21-43.zip](https://github.com/XLabsProject/s1x-client/files/6178518/s1x-crash-2-2021-03-21-23-21-43.zip)

**Comment by momo5502** [comment]
Will have a look later, I suppose this should be easy to fix

**Comment by diamante0018** [comment]
This is fixed
