### ISSUE TITLE
Rare crash when exiting private match menu

### ISSUE THREAD

**Issue by DAFFAsd** [XLabsProject/s1x-client#47]
Just got the first crash ive ever had in S1x. this appears when i want to exit private match menu (pressing esc)

[s1x-crash-2-2021-03-25-12-24-21.zip](https://github.com/XLabsProject/s1x-client/files/6202249/s1x-crash-2-2021-03-25-12-24-21.zip)
[s1x-crash-2-2021-03-25-12-24-16.zip](https://github.com/XLabsProject/s1x-client/files/6203600/s1x-crash-2-2021-03-25-12-24-16.zip)

(i forgot that it created 2 dumps)

**Comment by DAFFAsd** [comment]
![Screenshot_840](https://user-images.githubusercontent.com/76528397/112424046-50666300-8d66-11eb-9d58-85f8a5da47e2.png)

**Comment by diamante0018** [comment]
Can't replicate. Issue to old to work with.
