### ISSUE TITLE
Delete SP files

### ISSUE THREAD

**Issue by carvaofficial** [XLabsProject/s1x-client#488]
Hello, I need to know which files I should delete so that the campaign mode of the game does not take up space. Is this possible?

**Comment by diamante0018** [comment]
I don't know have an answer but these questions belong to the XLabs discord https://discord.gg/sKeVmR3
Someone might be able to help you in the s1x-support channel.
As this is not an issue with the client nor a question about the client itself but rather the game I'm closing this.
