### ISSUE TITLE
the mission get closed adter this error occurs...please help

### ISSUE THREAD

**Issue by vedant944** [XLabsProject/s1x-client#506]
![image](https://user-images.githubusercontent.com/66505092/199255929-7d3862a0-5442-4ce6-be30-df4a087ff7ef.png)

**Comment by diamante0018** [comment]
This is not helpful at all. Please upload the minidumps

**Comment by vedant944** [comment]
[Uploading s1x-crash-1-2022-11-01-00-27-08.zip…]()
[s1x-crash-1-2022-11-01-16-25-30.zip](https://github.com/XLabsProject/s1x-client/files/9910909/s1x-crash-1-2022-11-01-16-25-30.zip)
[Uploading s1x-crash-1-2022-11-01-16-27-22.zip…]()

**Comment by vedant944** [comment]
> This is not helpful at all. Please upload the minidumps

okay here are the dumps
[s1x-crash-1-2022-11-01-00-27-08.zip](https://github.com/XLabsProject/s1x-client/files/9910918/s1x-crash-1-2022-11-01-00-27-08.zip)
[s1x-crash-1-2022-11-01-16-25-30.zip](https://github.com/XLabsProject/s1x-client/files/9910923/s1x-crash-1-2022-11-01-16-25-30.zip)
[s1x-crash-1-2022-11-01-16-27-22.zip](https://github.com/XLabsProject/s1x-client/files/9910924/s1x-crash-1-2022-11-01-16-27-22.zip)

**Comment by diamante0018** [comment]
Double click xlabs to update. In other words: play the game

**Comment by vedant944** [comment]
but when i start the game and start single playes and play any level this error occur it do not occur when i open the launcher our enter the game it only shows when i start level

**Comment by diamante0018** [comment]
Set the xlabs launcher to the experimental update channel by going to the settings menu.
Please try again in 20 minutes or so. It will be fixed.

**Comment by vedant944** [comment]
it worked thank you so much💕💕😊😊
