### ISSUE TITLE
Crash When Damaged in Exo Zombies

### ISSUE THREAD

**Issue by timothyrose19** [XLabsProject/s1x-client#507]
I have an issue where my game crashes as soon as I take damage from a zombie or grenade in the exo zombies mode. I get the fatal error 0xC00000005. I can damage the zombies and do whatever I please so long as I don't take damage. Attached is my minidump. I have tried some things such as disabling shadow caching but still have this error.

[s1x-crash-5-2022-11-01-12-16-37.zip](https://github.com/XLabsProject/s1x-client/files/9912604/s1x-crash-5-2022-11-01-12-16-37.zip)

**Comment by mjkzy** [comment]
everything looks good on user's system and game files, crashes in 0x16003C76A

**Comment by timothyrose19** [comment]
This issue started after I tried to enable cheast with the "sv_cheats 1" command and trying to turn on god mode. I have tried to disable cheats, reinstall the game and xlabs launcher, and also restored my system to an earlier state but the problem persists. I believe that enabling cheats is what caused this initially.

**Comment by diamante0018** [comment]
You should have patiently waited 1 day instead of installing everything again and even go to the great length of restoring your system to an earlier state. As you can see the issue as since been resolved.

**Comment by timothyrose19** [comment]
I understand. What can I do on my end to fix this at this time?

**Comment by mjkzy** [comment]
just play the client
