### ISSUE TITLE
S1x Code 0xC0000005 When I try to start up Campaign.

### ISSUE THREAD

**Issue by Tiso88** [XLabsProject/s1x-client#527]
I just downloaded S1x today, and whenever I try to run the campaign, it brings me back to the menu screen with the error code 0xC0000005 and tells me to either close steam, update my drivers, or update my operating system. My drivers and operating system are up to date and it still doesn't work with steam closed. I've tried using the -nosteam with launch but that didn't help either. Can anyone help me? I'll link the full minidump below.
[info.txt](https://github.com/XLabsProject/s1x-client/files/9957697/info.txt)

**Comment by efinst0rm** [comment]
Please try and see if you get this error on the experimental branch. Hit the cog on xlabs launcher and switch from stable to experimental.

**Comment by Tiso88** [comment]
> Please try and see if you get this error on the experimental branch. Hit the cog on xlabs launcher and switch from stable to experimental.

This worked! Thank you so much, I've been trying at this for an hour and this fixed it!
