### ISSUE TITLE
Add support for IStrings in scripting

### ISSUE THREAD

**Issue by Joelrau** [XLabsProject/s1x-client#57]
`hud.label = "value: &&1"` crashes, since scripting doesn't have support for IStrings (type 3)

in gsc it would be `hud.label = &"value: &&1"`

**Comment by diamante0018** [comment]
With GSC support, I don't any benefit in adding this feature to LUA. In other words, I would recommend always using GSC over LUA.
If this was already done in another client, feel free to port it over.
Otherwise gonna close this.
