### ISSUE TITLE
Scoreboard Game Mode text does not update properly on Dedicated Servers

### ISSUE THREAD

**Issue by BoxOfMysteriez** [XLabsProject/s1x-client#573]
![S1xscorebug](https://user-images.githubusercontent.com/77655611/212511851-102f9204-6751-41ed-80de-0c7d6d0855ef.png)

**What are you trying to do?**
Have the game mode text on the scoreboard display the proper game mode on dedicated servers for all players

**What problem are you having?**
If I change the game mode on my dedicated server, after connecting to it again with the client the text on the scoreboard screen does not update. In the example picture provided, I've switched it from TDM to Uplink. The text on the scoreboard screen still reads "Team Deathmatch", however the game mode has changed and even the announcer says the correct game mode, so it's just a visual bug. I was only able to see this issue on dedicated servers, not private match. 

**What version of S1x are you using?**
2.1.0. Stable, fresh install, all updated. 

**Anything else we should know?**
Someone else in the discord had mentioned seeing this shortly after my post in the S1X support channel. So it seems not isolated to just me.

**Comment by diamante0018** [comment]
As I said on Discord, I was unable to replicate this issue.
I started my game on a dedicated server on "gun game", and then I connected with my client. After that, I closed the server and started it on "war". I connected with the same client from the main menu and the game type updated properly.

**Comment by BoxOfMysteriez** [comment]
updated the post to add more clarification
