### ISSUE TITLE
Unlocking Lootbox Items/Cosmetics without Unlocking Standard Ones

### ISSUE THREAD

**Issue by BoxOfMysteriez** [XLabsProject/s1x-client#578]
**What problem will this solve?**
Allow players who want to normally rank up/level guns/unlock camos to also obtain lootbox items via an unlock since otherwise there is no way of doing it without unlocking everything. 

**What might be a solution?**
It seems that H1-Mod has already done something similar to this within their stats menu selection. Given the shared code between the clients I can't imagine it would be hard to implement here. 

**What other alternatives have you already considered?**
Selecting to unlock everything via the stats menu or console command will unlock the lootbox exclusive items but will also unlock everything else, ruining the sense of progression. An alternative to this would be of course to implement a working supply drop feature. But I could imagine that'd be much more complicated than a simple lootbox-exclusive unlock 

**Anything else we should know?**
Provided an example screenshot of how this appears to work in H1-Mod. 
![unlockall-73c517898dc3d8790c15bd33b8e6fde5](https://user-images.githubusercontent.com/77655611/212594680-7e39a1a7-2ba6-4fb5-a3eb-5fdf9c9d0adb.png)

**Comment by diamante0018** [comment]
Feel free to make a pull request

**Comment by imbots7274** [comment]
wonfix?

**Comment by diamante0018** [comment]
Won't fix means the XLabs team is not going to work on this.
However you are free to do this on your own and send us your results via a pull request.

**Comment by diamante0018** [comment]
Won't, not planned. If anyone wants they are free to work on this on their own and submit a pull request.
