### ISSUE TITLE
Move publisher files outside of compiled application

### ISSUE THREAD

**Issue by WantedDV** [XLabsProject/s1x-client#585]
Is it possible to move the dw publisher files from `src/client/resources/dw` to the `data` folder so they are more accessible? 

**What problem will this solve?**
This would allow playlists to be modified without having to recompile the application. With a modified playlist, users would be able to matchmake and level up with bots. Using an open file format for the publisher files allows for easy customization of bot difficulty, XP scaling, etc.

I made a similar request for iw6x here: [https://github.com/XLabsProject/iw6x-client/issues/838](https://github.com/XLabsProject/iw6x-client/issues/838)

**Anything else we should know?**
Ayria used an open filesystem for publisher files.

**Comment by diamante0018** [comment]
Feel free to make a pull request
