### ISSUE TITLE
The server gets stuck here from time to time

### ISSUE THREAD

**Issue by monocolotion** [XLabsProject/s1x-client#588]
![3651e7e5300663dd9c033ed10c887c9](https://user-images.githubusercontent.com/105358544/213909171-a4ddac67-dae4-4fb9-87ea-2604c0561950.jpg)

**Comment by mjkzy** [comment]
from what i can tell, the server seems to be disconnecting from the game and back in the lobby menu? o_O

**Comment by monocolotion** [comment]
How to solve this problem Thank you in advance

> 据我所知，服务器似乎正在断开与游戏的连接并返回大厅菜单？o_O

**Comment by Dss0** [comment]
what does it say when you type "status" into the server console? Can you post your server config (remove rcon password if you have one set)

**Comment by monocolotion** [comment]
]status
map: mp_instinct
num score bot ping guid                             name             address               qport
--- ----- --- ---- -------------------------------- ---------------- --------------------- -----
  0     0 Yes  999                           bot121          RezTech                   bot   121
  1     0 Yes  999                           bot122       Flameducky                   bot   122
  2     0 Yes  999                           bot123         Diamante                   bot   123
  3     0 Yes  999                           bot124             sass                   bot   124
  4     0 Yes  999                           bot125       RektInator                   bot   125
  5     0 Yes  999                           bot126            H3X1C                   bot   126
  6     0 Yes  999                           bot127             Dsso                   bot   127
  7     0 Yes  999                           bot128            st0rm                   bot   128
  8     0 Yes  999                           bot129       FragsAreUs                   bot   129
  9     0 Yes  999                           bot130          RezTech                   bot   130
 10     0 Yes  999                           bot131        TheBigMan                   bot   131
 11     0 Yes  999                           bot132       RektInator                   bot   132
 12     0 Yes  999                           bot133             Evan                   bot   133
 13     0 Yes  999                           bot134       RektInator                   bot   134
 14     0 Yes  999                           bot135         Infamous                   bot   135
 16     0 Yes  999                           bot120            h8_mE                   bot   120

> 当您在服务器控制台中键入“状态”时，它说什么？你能发布你的服务器配置吗（如果你有一个设置，请删除 rcon 密码）

**Comment by Dss0** [comment]
looks like it's still running tho? can you connect?

**Comment by monocolotion** [comment]
> 看起来它仍在运行？你能连接吗？

Can connect 

I just rebooted it

**Comment by monocolotion** [comment]
> 

https://airportal.cn/102209/kIkCZsJ9Ew My server's configuration file

**Comment by monocolotion** [comment]
> 看起来它仍在运行？你能连接吗？

https://airportal.cn/102209/kIkCZsJ9Ew My server's configuration file

**Comment by Dss0** [comment]
Wait, did you type "status" while it was "stuck" or after you rebooted it? ofc it's gonna work after you reboot it..

**Comment by monocolotion** [comment]
> 等等，您是在“卡住”时还是在重新启动后键入“状态”？ofc 重新启动后它将工作。

After reboot

**Comment by monocolotion** [comment]
> 等等，您是在“卡住”时还是在重新启动后键入“状态”？ofc 重新启动后它将工作。

After a while, it may get stuck
I'll type it once when it gets stuck 
I don't speak English very well and communication may not be very smooth

**Comment by Dss0** [comment]
you have a typo in your map rotation. `map mp_bigben` does not exist, it's `mp_bigben2`. It will probably get stuck there.

**Comment by monocolotion** [comment]
> map mp_bigbend

I'll delete it
Thank you for helping me

**Comment by Dss0** [comment]
please report back if that fixed the freezing, otherwise type status and try connecting **while** it is frozen.

**Comment by diamante0018** [comment]
Closing this as support tickets do not belong to the GitHub but they belong to the XLabs Discord.
You may still post updates here but it seems you issue has already been handled @monocolotion

**Comment by monocolotion** [comment]
> 如果修复了冻结，请报告，否则键入状态并在冻结**时**尝试连接。

The server doesn't get stuck again
But it crashed due to insufficient memory
![image](https://user-images.githubusercontent.com/105358544/213965070-d2e30d6a-e57a-4709-822b-76f5f4f309ef.png)

**Comment by monocolotion** [comment]
> 如果修复了冻结，请报告，否则键入状态并在冻结**时**尝试连接。

<img width="315" alt="image" src="https://user-images.githubusercontent.com/105358544/214799632-794c8e5c-b0c2-48fa-a280-70423af9627d.png">
<img width="316" alt="image" src="https://user-images.githubusercontent.com/105358544/214799683-a4bb84f3-978d-43be-85cf-1f795db6e182.png">
The server is stuck again
