### ISSUE TITLE
Team balancing should never occour in Infected

### ISSUE THREAD

**Issue by BoxOfMysteriez** [XLabsProject/s1x-client#614]
**What are you trying to do?**
Play Infected on dedicated servers without the team balancing script activating by default 

**What problem are you having?**
When you play a match of "Infected" on dedicated servers, by default the team balancing script will initiate sometime after the game has started causing half the team to become Infected. Needless to say, that's not how the mode is supposed to work and it basically breaks it. 

**What version of S1x are you using?**
2.1.2 Stable Release. Latest Server configs

**Anything else we should know?**
This issue can be avoided by changing set scr_teambalance to 0 before a match of Infected is loaded. But will have to be toggled back on if you want to use it again in other game modes. This issue does not seem to be present in Private Match

**Comment by diamante0018** [comment]
Set scr_teambalance dvar to 0. thanks

**Comment by diamante0018** [comment]
https://github.com/XLabsProject/S1xServerConfigs/blob/master/s1x/server.cfg

**Comment by Rackover** [comment]
maybe we should rather tell him to try this dvar and come back to us if it's solved? so that we can make sure the issue has been resolved on their end by using this Dvar, before slamming the door on his face

**Comment by diamante0018** [comment]
> maybe we should rather tell him to try this dvar and come back to us if it's solved, rather than closing the issue immediatly? so that we can make sure the issue has been resolved on his end by using this Dvar, before slamming the door on his face

The question is being asked in the wrong place unfortunately, we encourage people to ask modding-related questions in the modding channel as per [get-help.md](https://github.com/XLabsProject/s1x-client/blob/develop/.github/ISSUE_TEMPLATE/get-help.md).

Next time I ought to either ignore the issue or close it straight away. So you are right I handled this incorrectly by giving the user the answer to fix the problem.

**Comment by mjkzy** [comment]
> Next time I ought to either ignore the issue or close it straight away. So you are right, I handled this incorrectly by giving the user the answer to fix the problem.

bro what kind of response is that lol? just tell bro to set the dvar to 0 and then ask questions in the discord if he needs further help
