### ISSUE TITLE
mouse wont look up

### ISSUE THREAD

**Issue by tacoman007777334** [XLabsProject/s1x-client#653]
so, the problem is when opening singeplayer everything works as it should. Starting multiplayer the game won't show my mouse when it starts i have to tab out the game then tab back in, then it sees my mouse. It sees the mouse and i start a private match to see if my mouse will work. but no i't won't do anything, i go around this by going to setting changing the screen to windowed then changing it back to window borderless, after this my mouse does work but only with looking to my left,right and down but not up. 

before this problem my game wouldn't even start (singeplayer would still work perfectly fine). I started the game by xlabs then it would be blank and then i would hear windows sounds and my mouse loading, i would have to go into task manager and force it down. i did nothing ot fix this and i can't redo it. i have been trying to fix these problems for the last 4 days but i don't find anyhing in the xlabs webiste besides stopping all overlays but that's it.

**Comment by diamante0018** [comment]
Support queries should be dealt with on the XLabs Discord server.
You can find a link to join it on the XLabs website.

**Comment by tacoman007777334** [comment]
sorry for posting here but i'm desperate and i have been on this issue since the evening of the 19th on discord but only got 1 person to respond and try to help but couldn't because he doesn't even know why this is happening.

**Comment by tacoman007777334** [comment]
and the fact that the advanced warefare side of the discord is almost dead doesn't really help it xp
