### ISSUE TITLE
s1x crash not letting me load up

### ISSUE THREAD

**Issue by dismurs** [XLabsProject/s1x-client#76]
[s1x-crash-2-2021-04-14-00-14-50.zip](https://github.com/XLabsProject/s1x-client/files/6307184/s1x-crash-2-2021-04-14-00-14-50.zip)

**Comment by momo5502** [comment]
This is an issue with steam. Try closing it. Steam will probably ship a bugfix for that. If it still occurs in the future, it might be a bad API call from our side, but I doubt things have changed.
