### ISSUE TITLE
Crashing when closing

### ISSUE THREAD

**Issue by zVPG** [XLabsProject/s1x-client#84]
When loading the plain S1x menu (Where you choose Singleplayer, Multiplayer, Survival Zombies) And you close out without selecting a gamemode, it crashes the application. 
![image](https://user-images.githubusercontent.com/46054954/114930500-b50f5d80-9dfa-11eb-8f89-384d55b58844.png)
![image](https://user-images.githubusercontent.com/46054954/114930520-b9d41180-9dfa-11eb-9d6f-3185f84c616e.png)

**Comment by momo5502** [comment]
Can you please try to reproduce this with the latest client? It should create a minidump.
I need this minidump for the analysis :)

**Comment by zVPG** [comment]
From what I can see, there is no minidump generated, and yes it is able to be reproduced on the latest client.
