### ISSUE TITLE
Check if fast file (dlc is missing) before joining server

### ISSUE THREAD

**Issue by diamante0018** [XLabsProject/s1x-client#87]
Feature request:
Attempting to join a server on a map not available on the client will abruptly close the game with the error displayed in the attachments.
![Capture](https://user-images.githubusercontent.com/37080671/115061686-c71bf980-9ee9-11eb-8057-8fd1c38d1a9c.PNG)
It would be nice if the client could check first if a map is first available before joining the server.

**Comment by momo5502** [comment]
Yeah, should be done, but we also provide the full game files, or the DLC files, so this has super low priority

**Comment by mjkzy** [comment]
in what way should this be implemented? as in it doesn't fatal crash you or it just doesn't let you connect to the server at all if you don't have the map the server is currently playing?

**Comment by diamante0018** [comment]
"in what way should this be implemented? as in it doesn't fatal crash you or it just doesn't let you connect to the server at all if you don't have the map the server is currently playing?"
Perhaps a good way would be to get a regular error message box so that it doesn't not fatal crash.

**Comment by mjkzy** [comment]
> "in what way should this be implemented? as in it doesn't fatal crash you or it just doesn't let you connect to the server at all if you don't have the map the server is currently playing?"
> Perhaps a good way would be to get a regular error message box so that it doesn't not fatal crash.

Sorry I deleted my comment :P was gonna look into doing it and it probably isn't hard to do but I didn't know in which way it would be implemented. Although, I may be able to make it not fatal crash and disconnect with a error or something.
