### ISSUE TITLE
2 or more players on the same network can't join the online and local server. 

### ISSUE THREAD

**Issue by FritasTechTips** [XLabsProject/s1x-client#88]
Seems a shared GUID a IP issue?!?

Player 1 connects and can spawn and roam around the map.
Players 2 connects > Player 1 gets server disconnected error message.
Player 1 connects > Player 2 gets server disconnected error message  just like Player 1.

Tested with a 3rd PC and sv_lanonly 1 local dedicated server. Same issue

IW6x seems to have the same issue.

**Comment by momo5502** [comment]
![image](https://user-images.githubusercontent.com/4027748/115073318-7233af80-9ef8-11eb-83f2-5bdd529eb9a1.png)

**Comment by momo5502** [comment]
Works fine on my end. Probably an issue with your network, firewall, router or ISP.

![Unbenannt](https://user-images.githubusercontent.com/4027748/115073450-a4451180-9ef8-11eb-96d7-6450df6baa08.PNG)

**Comment by FritasTechTips** [comment]
Everything default with Linksys WRT1900ACS. IW4x and Plutonium works perfectly fine. Just s1X and IW6x only issue I having. I even tried a unmanaged switch and still same issue.
