### ISSUE TITLE
built executable wont do anything

### ISSUE THREAD

**Issue by Pacoca-BR240** [XLabsProject/s1x-client#89]
i followed the instructions and built the .sln on visual studio, and the result was a file named runner.exe with s1x logo. i pasted it inside s1x game folder, disabled fullscreen optimizations and set it to run as admin but it wont even open.

**Comment by diamante0018** [comment]
I'm your build environment you should have 2 files with a 
.exe and a dll file. You should paste those 3 files one the game folder and then run s1.exe.
Anyway the client will be released on the 20th and you will be able to download pre compiled binaries.

**Comment by OneFourOne** [comment]
First, please just wait till the 20th because it's clear that you haven't build s1x properly. Runner is not what you run...
> You should paste those 3 files in the game folder and then run s1.exe.
That is also incorrect, all you need is s1x.exe
