### ISSUE TITLE
Serverlist connect issue

### ISSUE THREAD

**Issue by Brentdevent** [XLabsProject/s1x-client#92]
When clicking to join a server in the list it connects you to another server. 
It doesn't happen all the time.

https://cdn.discordapp.com/attachments/822759254095167488/833084250227867678/2021-04-17_22-58-09.mp4

**Comment by momo5502** [comment]
I think i know why it happens. Everytime a server responds, it gets filled into the list, but the ui probably doesn't update

**Comment by Brentdevent** [comment]
Video with debug print message in console:
https://cdn.discordapp.com/attachments/822759254095167488/833104583571800074/2021-04-18_00-17-02.mp4

I have also noticed this, perhaps it could help as well.
![image](https://user-images.githubusercontent.com/70229620/115128948-bb136300-9fe1-11eb-94d5-f97d59eaaafd.png)
![image](https://user-images.githubusercontent.com/70229620/115128950-c49ccb00-9fe1-11eb-92f1-e3e1ef55328e.png)

The server at index zero is not showing in the ui.

**Comment by momo5502** [comment]
![image](https://user-images.githubusercontent.com/4027748/115140129-0ce5d880-a036-11eb-844d-61828427b639.png)

**Comment by momo5502** [comment]
Still, props to @Brentdevent, cause he also pretty much figured it out, but I have seen his findings only after having pushed the fix alreay.
